name: "GH Build"
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
env:
  REGISTRY_IMAGE: getlago/api
  REGISTRY: ghcr.io
  
jobs:
  build-api-image:
    runs-on: ubuntu-latest
    name: Build API Image
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log In to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add version into docker image
        id: add_version
        run: |
          echo "${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.version }}" > LAGO_VERSION

      - name: Docker tag
        id: docker_tag
        run: echo "version=${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: "${{ env.REGISTRY }}/${{ github.repository_owner }}/lago-api:${{ steps.docker_tag.outputs.version }}-amd64"
